INSERT INTO COURSE (ID, NAME) VALUES (1, 'Spring course');
INSERT INTO COURSE (ID, NAME) VALUES (2, 'Java course');
INSERT INTO COURSE (ID, NAME) VALUES (3, 'SQL course');

INSERT INTO STUDENT (ID, COURSE_ID, NAME, GRADE) VALUES (1, 1, 'Peter', 'B');
INSERT INTO STUDENT (ID, COURSE_ID, NAME, GRADE) VALUES (2, 1, 'Kevin', 'E');
INSERT INTO STUDENT (ID, COURSE_ID, NAME, GRADE) VALUES (3, 1, 'Jack', 'A');
INSERT INTO STUDENT (ID, COURSE_ID, NAME, GRADE) VALUES (4, 2, 'John', 'E');
INSERT INTO STUDENT (ID, COURSE_ID, NAME, GRADE) VALUES (5, 2, 'Sam', 'FX');
INSERT INTO STUDENT (ID, COURSE_ID, NAME, GRADE) VALUES (6, 3, 'Rick', null);
INSERT INTO STUDENT (ID, COURSE_ID, NAME, GRADE) VALUES (7, 3, 'Danny', null);